ProjetoEstudoCompra/Models/ErrorViewModel.cs
using System;

namespace ProjetoEstudoCompra.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoEstudoCompra/Models/LoginView.cs
namespace ProjetoEstudoCompra.Models
{
    public class LoginView
    {
        public int LoginId { get; set; }

        public string Usuario { get; set; }

        public string Senha { get; set; }

        public string Email { get; set; }

        public string Perfil { get; set; }
    }
}

ProjetoEstudoCompra/Controllers/LogarController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjetoEstudoCompra.Controllers
{
    public class LogarController : Controller
    {
        public IActionResult Entrar()
        {
            return View();
        }
    }
}

ProjetoEstudoCompra/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoEstucoCompra.Entidade.Entidade;
using ProjetoEstudoCompra.Models;
using ProjetoEstudoCompra.Servico.Servico;

namespace ProjetoEstudoCompra.Controllers
{
    public class LoginController : Controller
    {
        private readonly LoginServico loginServico;

        public LoginController()
        {
            loginServico = new LoginServico();
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult CadastrarLogin(LoginView loginView)
        {
            loginView = new LoginView();
            Login login = new Login();
            loginView.Usuario = login.Usuario;
            loginView.Senha = login.Senha;
            loginView.Email = login.Email;
            loginView.Perfil = login.Perfil;
            loginServico.Cadastrar(login);
            return RedirectToAction("Cadastro", "Login");
        }
    }
}

ProjetoEstudoCompra/Views/Logar/Entrar.cshtml
@model ProjetoEstudoCompra.Models.LoginView
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="modal-dialog">
    <div class="modal-content">
    @using (Html.BeginForm())
    {
        <div class="modal-header">
            <h4 class="modal-title">Cadastrar Usuario</h4>
        </div>

         <div class="modal-body">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                

                <div class="form-group">
                    @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                    </div>
                </div>

                

              </div>
            </div>
            <div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Logar no sistema" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
                }
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->

      <div>
    }
</div>

ProjetoEstudoCompra/Views/Login/Cadastrar.cshtml
@model ProjetoEstudoCompra.Models.LoginView
@*
    cadastrar o usuario  
*@
@{
}


<div class="modal-dialog">
    <div class="modal-content">
    @using (Html.BeginForm("CadastrarLogin","Login"))
    {
        <div class="modal-header">
            <h4 class="modal-title">Cadastrar Usuario</h4>
        </div>

         <div class="modal-body">
            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                

                <div class="form-group">
                    @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.PasswordFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Perfil, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Perfil, new List<SelectListItem>
                        {
                            new SelectListItem { Text = "Gerente", Value="gerente" },
                            new SelectListItem { Text = "Funcionario", Value="funcionario" }
                        }, 
              "Selecione um item", new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Perfil, "", new { @class = "text-danger" })
                    </div>
                </div>

              </div>
            </div>
            <div class="modal-footer">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Salvar" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
                }
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->

      <div>
    }
</div>

ProjetoEstudoCompra/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoEstudoCompra</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">@Html.ActionLink("Cadastrar Usuario","Cadastrar","Login")</a></li>
                    <li><a href="#">@Html.ActionLink("Logar Usuario","Entrar","Logar")</a></li>
                    
                </ul>
            </div>
        </div>
    </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetoEstudoCompra - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>